/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividadetpr;

/**
 *
 * @author User
 */
public class quizJava extends javax.swing.JFrame {

    /**
     * Creates new form quizJava
     */
    public quizJava() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp1 = new javax.swing.ButtonGroup();
        btnGrp2 = new javax.swing.ButtonGroup();
        btnGrp3 = new javax.swing.ButtonGroup();
        btnGrp4 = new javax.swing.ButtonGroup();
        btnGrp5 = new javax.swing.ButtonGroup();
        btnGrp6 = new javax.swing.ButtonGroup();
        btnGrp7 = new javax.swing.ButtonGroup();
        btnGrp8 = new javax.swing.ButtonGroup();
        btnGrp9 = new javax.swing.ButtonGroup();
        btnGrp10 = new javax.swing.ButtonGroup();
        pnlPrincipal = new javax.swing.JPanel();
        pnlquiz1 = new javax.swing.JPanel();
        jrbOPCa = new javax.swing.JRadioButton();
        jrbOPCb = new javax.swing.JRadioButton();
        jrbOPCc = new javax.swing.JRadioButton();
        jrbOPCd = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        pnlquiz2 = new javax.swing.JPanel();
        jrbA2 = new javax.swing.JRadioButton();
        jrbB2 = new javax.swing.JRadioButton();
        jrbC2 = new javax.swing.JRadioButton();
        jrbD2 = new javax.swing.JRadioButton();
        pnlquiz3 = new javax.swing.JPanel();
        jrbA3 = new javax.swing.JRadioButton();
        jrbB3 = new javax.swing.JRadioButton();
        jrbC3 = new javax.swing.JRadioButton();
        jrbD3 = new javax.swing.JRadioButton();
        pnlquiz4 = new javax.swing.JPanel();
        jrbA4 = new javax.swing.JRadioButton();
        jrbB4 = new javax.swing.JRadioButton();
        jrbC4 = new javax.swing.JRadioButton();
        jrbD4 = new javax.swing.JRadioButton();
        pnlquiz5 = new javax.swing.JPanel();
        jrbA5 = new javax.swing.JRadioButton();
        jrbB5 = new javax.swing.JRadioButton();
        jrbC5 = new javax.swing.JRadioButton();
        jrbD5 = new javax.swing.JRadioButton();
        pnlquiz6 = new javax.swing.JPanel();
        jrbA6 = new javax.swing.JRadioButton();
        jrbB6 = new javax.swing.JRadioButton();
        jrbC6 = new javax.swing.JRadioButton();
        jrbD6 = new javax.swing.JRadioButton();
        pnlquiz7 = new javax.swing.JPanel();
        jrbA7 = new javax.swing.JRadioButton();
        jrbB7 = new javax.swing.JRadioButton();
        jrbC7 = new javax.swing.JRadioButton();
        jrbD7 = new javax.swing.JRadioButton();
        pnlquiz8 = new javax.swing.JPanel();
        jrbA8 = new javax.swing.JRadioButton();
        jrbB8 = new javax.swing.JRadioButton();
        jrbC8 = new javax.swing.JRadioButton();
        jrbD8 = new javax.swing.JRadioButton();
        pnlquiz9 = new javax.swing.JPanel();
        jrbA9 = new javax.swing.JRadioButton();
        jrbB9 = new javax.swing.JRadioButton();
        jrbC9 = new javax.swing.JRadioButton();
        jrbD9 = new javax.swing.JRadioButton();
        pnlquiz10 = new javax.swing.JPanel();
        jrbA10 = new javax.swing.JRadioButton();
        jrbB10 = new javax.swing.JRadioButton();
        jrbC10 = new javax.swing.JRadioButton();
        jrbD10 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.CardLayout());

        pnlquiz1.setBackground(new java.awt.Color(0, 0, 0));
        pnlquiz1.setForeground(new java.awt.Color(255, 255, 255));

        btnGrp1.add(jrbOPCa);
        jrbOPCa.setText("jRadioButton1");

        btnGrp1.add(jrbOPCb);
        jrbOPCb.setText("jRadioButton2");

        btnGrp1.add(jrbOPCc);
        jrbOPCc.setText("jRadioButton3");

        btnGrp1.add(jrbOPCd);
        jrbOPCd.setText("jRadioButton4");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout pnlquiz1Layout = new javax.swing.GroupLayout(pnlquiz1);
        pnlquiz1.setLayout(pnlquiz1Layout);
        pnlquiz1Layout.setHorizontalGroup(
            pnlquiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pnlquiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrbOPCb)
                    .addComponent(jrbOPCa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(pnlquiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbOPCc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrbOPCd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(58, 58, 58))
            .addGroup(pnlquiz1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlquiz1Layout.setVerticalGroup(
            pnlquiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addGap(96, 96, 96)
                .addGroup(pnlquiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbOPCa)
                    .addComponent(jrbOPCc))
                .addGap(36, 36, 36)
                .addGroup(pnlquiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbOPCb)
                    .addComponent(jrbOPCd))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlquiz1, "card3");

        pnlquiz2.setBackground(new java.awt.Color(51, 51, 51));

        btnGrp2.add(jrbA2);
        jrbA2.setText("jRadioButton1");
        jrbA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbA2ActionPerformed(evt);
            }
        });

        btnGrp2.add(jrbB2);
        jrbB2.setText("jRadioButton2");

        btnGrp2.add(jrbC2);
        jrbC2.setText("jRadioButton3");

        btnGrp2.add(jrbD2);
        jrbD2.setText("jRadioButton4");

        javax.swing.GroupLayout pnlquiz2Layout = new javax.swing.GroupLayout(pnlquiz2);
        pnlquiz2.setLayout(pnlquiz2Layout);
        pnlquiz2Layout.setHorizontalGroup(
            pnlquiz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlquiz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlquiz2Layout.createSequentialGroup()
                        .addComponent(jrbC2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(jrbD2))
                    .addGroup(pnlquiz2Layout.createSequentialGroup()
                        .addComponent(jrbA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrbB2)))
                .addGap(58, 58, 58))
        );
        pnlquiz2Layout.setVerticalGroup(
            pnlquiz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz2Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(pnlquiz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbA2)
                    .addComponent(jrbB2))
                .addGap(44, 44, 44)
                .addGroup(pnlquiz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbC2)
                    .addComponent(jrbD2))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlquiz2, "card4");

        pnlquiz3.setBackground(new java.awt.Color(0, 0, 0));

        btnGrp3.add(jrbA3);
        jrbA3.setText("jRadioButton1");

        btnGrp3.add(jrbB3);
        jrbB3.setText("jRadioButton2");

        btnGrp3.add(jrbC3);
        jrbC3.setText("jRadioButton3");

        btnGrp3.add(jrbD3);
        jrbD3.setText("jRadioButton4");

        javax.swing.GroupLayout pnlquiz3Layout = new javax.swing.GroupLayout(pnlquiz3);
        pnlquiz3.setLayout(pnlquiz3Layout);
        pnlquiz3Layout.setHorizontalGroup(
            pnlquiz3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlquiz3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlquiz3Layout.createSequentialGroup()
                        .addComponent(jrbC3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(jrbD3))
                    .addGroup(pnlquiz3Layout.createSequentialGroup()
                        .addComponent(jrbA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrbB3)))
                .addGap(58, 58, 58))
        );
        pnlquiz3Layout.setVerticalGroup(
            pnlquiz3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz3Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(pnlquiz3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbA3)
                    .addComponent(jrbB3))
                .addGap(31, 31, 31)
                .addGroup(pnlquiz3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbC3)
                    .addComponent(jrbD3))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlquiz3, "card4");

        pnlquiz4.setBackground(new java.awt.Color(51, 51, 51));

        btnGrp4.add(jrbA4);
        jrbA4.setText("jRadioButton5");

        btnGrp4.add(jrbB4);
        jrbB4.setText("jRadioButton6");

        btnGrp4.add(jrbC4);
        jrbC4.setText("jRadioButton7");

        btnGrp4.add(jrbD4);
        jrbD4.setText("jRadioButton8");

        javax.swing.GroupLayout pnlquiz4Layout = new javax.swing.GroupLayout(pnlquiz4);
        pnlquiz4.setLayout(pnlquiz4Layout);
        pnlquiz4Layout.setHorizontalGroup(
            pnlquiz4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnlquiz4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrbC4)
                    .addComponent(jrbA4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(pnlquiz4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbB4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrbD4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(58, 58, 58))
        );
        pnlquiz4Layout.setVerticalGroup(
            pnlquiz4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz4Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(pnlquiz4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbA4)
                    .addComponent(jrbB4))
                .addGap(43, 43, 43)
                .addGroup(pnlquiz4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbC4)
                    .addComponent(jrbD4))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlquiz4, "card5");

        pnlquiz5.setBackground(new java.awt.Color(0, 0, 0));

        btnGrp5.add(jrbA5);
        jrbA5.setText("jRadioButton9");

        btnGrp5.add(jrbB5);
        jrbB5.setText("jRadioButton10");

        btnGrp5.add(jrbC5);
        jrbC5.setText("jRadioButton11");
        jrbC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbC5ActionPerformed(evt);
            }
        });

        btnGrp5.add(jrbD5);
        jrbD5.setText("jRadioButton12");

        javax.swing.GroupLayout pnlquiz5Layout = new javax.swing.GroupLayout(pnlquiz5);
        pnlquiz5.setLayout(pnlquiz5Layout);
        pnlquiz5Layout.setHorizontalGroup(
            pnlquiz5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlquiz5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jrbA5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbC5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(pnlquiz5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbD5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrbB5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(56, 56, 56))
        );
        pnlquiz5Layout.setVerticalGroup(
            pnlquiz5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz5Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(pnlquiz5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbA5)
                    .addComponent(jrbB5))
                .addGap(42, 42, 42)
                .addGroup(pnlquiz5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbC5)
                    .addComponent(jrbD5))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlquiz5, "card6");

        pnlquiz6.setBackground(new java.awt.Color(51, 51, 51));

        btnGrp6.add(jrbA6);
        jrbA6.setText("jRadioButton1");

        btnGrp6.add(jrbB6);
        jrbB6.setText("jRadioButton2");

        btnGrp6.add(jrbC6);
        jrbC6.setText("jRadioButton3");

        btnGrp6.add(jrbD6);
        jrbD6.setText("jRadioButton4");

        javax.swing.GroupLayout pnlquiz6Layout = new javax.swing.GroupLayout(pnlquiz6);
        pnlquiz6.setLayout(pnlquiz6Layout);
        pnlquiz6Layout.setHorizontalGroup(
            pnlquiz6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlquiz6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrbC6)
                    .addComponent(jrbA6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(pnlquiz6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbB6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrbD6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(54, 54, 54))
        );
        pnlquiz6Layout.setVerticalGroup(
            pnlquiz6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz6Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(pnlquiz6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbA6)
                    .addComponent(jrbB6))
                .addGap(49, 49, 49)
                .addGroup(pnlquiz6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbC6)
                    .addComponent(jrbD6))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlquiz6, "card7");

        pnlquiz7.setBackground(new java.awt.Color(0, 0, 0));

        btnGrp7.add(jrbA7);
        jrbA7.setText("jRadioButton1");

        btnGrp7.add(jrbB7);
        jrbB7.setText("jRadioButton2");
        jrbB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbB7ActionPerformed(evt);
            }
        });

        btnGrp7.add(jrbC7);
        jrbC7.setText("jRadioButton3");

        btnGrp7.add(jrbD7);
        jrbD7.setText("jRadioButton4");

        javax.swing.GroupLayout pnlquiz7Layout = new javax.swing.GroupLayout(pnlquiz7);
        pnlquiz7.setLayout(pnlquiz7Layout);
        pnlquiz7Layout.setHorizontalGroup(
            pnlquiz7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlquiz7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrbC7)
                    .addComponent(jrbA7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addGroup(pnlquiz7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbB7)
                    .addComponent(jrbD7))
                .addGap(50, 50, 50))
        );
        pnlquiz7Layout.setVerticalGroup(
            pnlquiz7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz7Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(pnlquiz7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbA7)
                    .addComponent(jrbB7))
                .addGap(61, 61, 61)
                .addGroup(pnlquiz7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbC7)
                    .addComponent(jrbD7))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlquiz7, "card8");

        pnlquiz8.setBackground(new java.awt.Color(51, 51, 51));

        btnGrp8.add(jrbA8);
        jrbA8.setText("jRadioButton5");

        btnGrp8.add(jrbB8);
        jrbB8.setText("jRadioButton6");

        btnGrp8.add(jrbC8);
        jrbC8.setText("jRadioButton7");

        btnGrp8.add(jrbD8);
        jrbD8.setText("jRadioButton8");

        javax.swing.GroupLayout pnlquiz8Layout = new javax.swing.GroupLayout(pnlquiz8);
        pnlquiz8.setLayout(pnlquiz8Layout);
        pnlquiz8Layout.setHorizontalGroup(
            pnlquiz8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz8Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(pnlquiz8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrbC8)
                    .addComponent(jrbA8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(pnlquiz8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbB8)
                    .addComponent(jrbD8))
                .addGap(68, 68, 68))
        );
        pnlquiz8Layout.setVerticalGroup(
            pnlquiz8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz8Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(pnlquiz8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbA8)
                    .addComponent(jrbB8))
                .addGap(48, 48, 48)
                .addGroup(pnlquiz8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbC8)
                    .addComponent(jrbD8))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlquiz8, "card9");

        pnlquiz9.setBackground(new java.awt.Color(0, 0, 0));

        btnGrp9.add(jrbA9);
        jrbA9.setText("jRadioButton9");

        btnGrp9.add(jrbB9);
        jrbB9.setText("jRadioButton10");

        btnGrp9.add(jrbC9);
        jrbC9.setText("jRadioButton11");

        btnGrp9.add(jrbD9);
        jrbD9.setText("jRadioButton13");

        javax.swing.GroupLayout pnlquiz9Layout = new javax.swing.GroupLayout(pnlquiz9);
        pnlquiz9.setLayout(pnlquiz9Layout);
        pnlquiz9Layout.setHorizontalGroup(
            pnlquiz9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz9Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(pnlquiz9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbA9)
                    .addComponent(jrbC9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(pnlquiz9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbB9)
                    .addComponent(jrbD9))
                .addGap(60, 60, 60))
        );
        pnlquiz9Layout.setVerticalGroup(
            pnlquiz9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz9Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(pnlquiz9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbA9)
                    .addComponent(jrbB9))
                .addGap(59, 59, 59)
                .addGroup(pnlquiz9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbC9)
                    .addComponent(jrbD9))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlquiz9, "card10");

        pnlquiz10.setBackground(new java.awt.Color(51, 51, 51));

        btnGrp10.add(jrbA10);
        jrbA10.setText("jRadioButton14");

        btnGrp10.add(jrbB10);
        jrbB10.setText("jRadioButton15");

        btnGrp10.add(jrbC10);
        jrbC10.setText("jRadioButton16");

        btnGrp10.add(jrbD10);
        jrbD10.setText("jRadioButton17");

        javax.swing.GroupLayout pnlquiz10Layout = new javax.swing.GroupLayout(pnlquiz10);
        pnlquiz10.setLayout(pnlquiz10Layout);
        pnlquiz10Layout.setHorizontalGroup(
            pnlquiz10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz10Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnlquiz10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbA10)
                    .addComponent(jrbC10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(pnlquiz10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbB10)
                    .addComponent(jrbD10))
                .addGap(52, 52, 52))
        );
        pnlquiz10Layout.setVerticalGroup(
            pnlquiz10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlquiz10Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(pnlquiz10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbA10)
                    .addComponent(jrbB10))
                .addGap(50, 50, 50)
                .addGroup(pnlquiz10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbC10)
                    .addComponent(jrbD10))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pnlPrincipal.add(pnlquiz10, "card11");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atividadetpr/editSWars.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        btn1.setText("1");

        btn2.setText("2");

        btn3.setText("3");

        btn4.setText("4");

        btn5.setText("5");

        btn6.setText("6");

        btn7.setText("7");

        btn8.setText("9");

        btn9.setText("8");

        btn10.setText("Anterior");

        btnAnt.setText("10");

        btnNext.setText("Próximo");

        btnResult.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn10)
                .addGap(28, 28, 28)
                .addComponent(btnNext)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnResult)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3)
                    .addComponent(btn4)
                    .addComponent(btn5)
                    .addComponent(btn10)
                    .addComponent(btnNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn6)
                    .addComponent(btn7)
                    .addComponent(btn9)
                    .addComponent(btn8)
                    .addComponent(btnAnt)
                    .addComponent(btnResult))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbA2ActionPerformed

    private void jrbC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbC5ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jrbC5ActionPerformed

    private void jrbB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbB7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbB7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quizJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quizJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quizJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quizJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new quizJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAnt;
    private javax.swing.ButtonGroup btnGrp1;
    private javax.swing.ButtonGroup btnGrp10;
    private javax.swing.ButtonGroup btnGrp2;
    private javax.swing.ButtonGroup btnGrp3;
    private javax.swing.ButtonGroup btnGrp4;
    private javax.swing.ButtonGroup btnGrp5;
    private javax.swing.ButtonGroup btnGrp6;
    private javax.swing.ButtonGroup btnGrp7;
    private javax.swing.ButtonGroup btnGrp8;
    private javax.swing.ButtonGroup btnGrp9;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jrbA10;
    private javax.swing.JRadioButton jrbA2;
    private javax.swing.JRadioButton jrbA3;
    private javax.swing.JRadioButton jrbA4;
    private javax.swing.JRadioButton jrbA5;
    private javax.swing.JRadioButton jrbA6;
    private javax.swing.JRadioButton jrbA7;
    private javax.swing.JRadioButton jrbA8;
    private javax.swing.JRadioButton jrbA9;
    private javax.swing.JRadioButton jrbB10;
    private javax.swing.JRadioButton jrbB2;
    private javax.swing.JRadioButton jrbB3;
    private javax.swing.JRadioButton jrbB4;
    private javax.swing.JRadioButton jrbB5;
    private javax.swing.JRadioButton jrbB6;
    private javax.swing.JRadioButton jrbB7;
    private javax.swing.JRadioButton jrbB8;
    private javax.swing.JRadioButton jrbB9;
    private javax.swing.JRadioButton jrbC10;
    private javax.swing.JRadioButton jrbC2;
    private javax.swing.JRadioButton jrbC3;
    private javax.swing.JRadioButton jrbC4;
    private javax.swing.JRadioButton jrbC5;
    private javax.swing.JRadioButton jrbC6;
    private javax.swing.JRadioButton jrbC7;
    private javax.swing.JRadioButton jrbC8;
    private javax.swing.JRadioButton jrbC9;
    private javax.swing.JRadioButton jrbD10;
    private javax.swing.JRadioButton jrbD2;
    private javax.swing.JRadioButton jrbD3;
    private javax.swing.JRadioButton jrbD4;
    private javax.swing.JRadioButton jrbD5;
    private javax.swing.JRadioButton jrbD6;
    private javax.swing.JRadioButton jrbD7;
    private javax.swing.JRadioButton jrbD8;
    private javax.swing.JRadioButton jrbD9;
    private javax.swing.JRadioButton jrbOPCa;
    private javax.swing.JRadioButton jrbOPCb;
    private javax.swing.JRadioButton jrbOPCc;
    private javax.swing.JRadioButton jrbOPCd;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlquiz1;
    private javax.swing.JPanel pnlquiz10;
    private javax.swing.JPanel pnlquiz2;
    private javax.swing.JPanel pnlquiz3;
    private javax.swing.JPanel pnlquiz4;
    private javax.swing.JPanel pnlquiz5;
    private javax.swing.JPanel pnlquiz6;
    private javax.swing.JPanel pnlquiz7;
    private javax.swing.JPanel pnlquiz8;
    private javax.swing.JPanel pnlquiz9;
    // End of variables declaration//GEN-END:variables
}
